### ISSUE TITLE
IM2 interrupt causes crash/reset

### ISSUE THREAD

**Issue by lippmaje** [ref-xx/basinc#13]
BasinC 1.794

See attached BAS and TAP file. The demo creates an interrupt routine in IM2 mode.
The routine just increases the byte at 16384 and jumps to the standard interrupt.
It's expected for the Basic program to continue with the print "test" statement for any key pressed.
In BasinC however, there's no waiting for the key (PAUSE 0 just returns happily) and when the "scroll?" prompt is acknowledged the IDE resets.
The program works as expected in FUSE and ZX Spin (you can even break into the program and see the interrupt continuing its duty.)
See also attached screens for how it should look like.
![IM2-bug](https://github.com/ref-xx/basinc/assets/87007255/35d99945-30c7-43c2-a842-a7a965f3b159)
![IM2-ok-FUSE](https://github.com/ref-xx/basinc/assets/87007255/56bafc21-1466-4280-8ae4-0cbf3028cce6)
[IM2-bug.zip](https://github.com/ref-xx/basinc/files/13855813/IM2-bug.zip)

**Comment by ref-xx** [comment]
because basinC needs many traps to work, modifying interrupt vectors can lead to erratic behaviour. BasinC is for basic programs, emulation core is limited to execute sinclair basic. although there is an assembler and compiler, those functions are never completed and never supported. I might remove those functions in the future to eliminate further confusion.
