### ISSUE TITLE
Variables window crashes BasinC

### ISSUE THREAD

**Issue by lippmaje** [ref-xx/basinc#21]
v1.794

Please open attached bas file and open the Variables window before running the program.
On my system I see a few variables popping up in the window and then nothing, the whole IDE stalls. (keine Rückmeldung = No response)
The IDE needs to be shut down afterwards.

The workaround is to make sure that Variables is closed before running the program. The program will then start normally, and it causes no harm when the Variables window will be opened thereafter.

This is the first time I noticed this with 1.794. It was never a problem to have the Variables window open all the time, so I am a bit at a loss to provide more clues to you. I have the IDE installation as downloaded, no addons, Windows 7 SP1.

![Variables-bug](https://github.com/user-attachments/assets/2cf65047-fafb-4dc7-baed-9b4041eede72)
[Variables-bug.bas.zip](https://github.com/user-attachments/files/17657813/Variables-bug.bas.zip)

**Comment by ref-xx** [comment]
ohh, nasty bug, tried to trace, this will not be easy. noted at the top of the buglist.

**Comment by lippmaje** [comment]
> ohh, nasty bug, tried to trace, this will not be easy. 

Can you provide a step by step list how to set up the development environment on Windows? I can then try to debug on my own and share results.

**Comment by ref-xx** [comment]
ok, checking on older versions of basinC and found out the bug was there since V1.5 but not before it. Anyway, the bug was due to creating string array for varswindow somehow skips the end marker and goes on an on. 

I don't have enough time to fix the issue for good, but added checks to prevent the overflow and it looks like it kind of fixed the issue of locking up, though built string arrays might come out wrong in the vars vindow.

For build environment, as there are some copyrighted packages, I cannot share more than it is available on github profile. I am also using a very old windowsXP+delphi5 HD image due to this. But I'm all in if you want to move/fork all the code to a newer dev env.  But it's a very big project, it will consume huge amount of time.

I'm marking this one for FIXED.
